use_default_settings: true

server:
  secret_key: "HIER_ERSETZEN_openssl_rand_-hex_32"
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: ""
  default_lang: "de-DE"
  max_page: 1

engines:
  - name: startpage
    engine: startpage
    shortcut: sp
    categories: general

  - name: google news
    engine: google_news
    shortcut: gn
    categories: news

  - name: github
    engine: github
    shortcut: gh
    categories: it

  - name: arxiv
    engine: arxiv
    shortcut: arx
    categories: science

  - name: semantic scholar
    engine: semantic_scholar
    shortcut: ss
    categories: science

  - name: pubmed
    engine: pubmed
    shortcut: pm
    categories: science

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0

ui:
  static_use_hash: true

enabled_plugins:
  - "Basic Calculator"
  - "Hash plugin"
  - "Self Informations"
  - "Tracker URL remover"
